/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.DoctorForms;
import users.DoctorSystem.AppointmentControlSys;
import java.util.*;
import javax.swing.JOptionPane;
import usersdata.DoctorUser;
/**
 *
 * @author joshh
 */
public class AppointmentControls extends javax.swing.JFrame {
    AppointmentControlSys c = new AppointmentControlSys();
    /**
     * Creates new form AppointmentControls
     */
    public AppointmentControls() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbxPatId = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAppNotes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        btnAppendNotes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtHistory = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cmbxAppointment = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbxMeds = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDosage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtPrescriptNotes = new javax.swing.JTextField();
        btnCreatePrescript = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnMarkAttended = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        cmbxPatId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxPatIdItemStateChanged(evt);
            }
        });
        cmbxPatId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxPatIdActionPerformed(evt);
            }
        });

        jLabel1.setText("Appointment Controls");

        jLabel2.setText("Patient ID: ");

        txtAppNotes.setColumns(20);
        txtAppNotes.setRows(5);
        jScrollPane1.setViewportView(txtAppNotes);

        jLabel3.setText("Appointment Notes:");

        btnAppendNotes.setText("Append Notes");
        btnAppendNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppendNotesActionPerformed(evt);
            }
        });

        txtHistory.setColumns(20);
        txtHistory.setRows(5);
        jScrollPane2.setViewportView(txtHistory);

        jLabel4.setText("Patient History:");

        cmbxAppointment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbxAppointment.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbxAppointmentItemStateChanged(evt);
            }
        });

        jLabel5.setText("Appointment:");

        jLabel6.setText("Prescribe Medicine:");

        cmbxMeds.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None" }));

        jLabel7.setText("Medicines:");

        jLabel8.setText("Dosage:");

        jLabel9.setText("Prescription Notes:");

        btnCreatePrescript.setText("Create Prescription");
        btnCreatePrescript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePrescriptActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnMarkAttended.setText("Mark as Attended");
        btnMarkAttended.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkAttendedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbxPatId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbxAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMarkAttended)
                    .addComponent(btnCreatePrescript)
                    .addComponent(btnAppendNotes)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrescriptNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbxMeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 25, Short.MAX_VALUE))
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxPatId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAppendNotes)
                .addGap(9, 9, 9)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbxMeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDosage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtPrescriptNotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCreatePrescript)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnMarkAttended)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppendNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppendNotesActionPerformed
        // TODO add your handling code here:
        String notes = txtAppNotes.getText();
        String patientId = cmbxPatId.getSelectedItem().toString();
        String selectedApp = cmbxAppointment.getSelectedItem().toString();
        Boolean complete = c.appendAppNotes(notes, patientId, selectedApp);
        if (complete == true){
            JOptionPane.showMessageDialog(null, "Notes successfully appended to patient: "+patientId+" Appointment date: "+selectedApp, "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAppendNotesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        ArrayList<String> patIds = c.getPatientIds();
        for(int i = 0; i < patIds.size(); i++){
            cmbxPatId.addItem(patIds.get(i));
        }
        
        ArrayList<String> medicines = c.getMedicines();
        for(int i = 0; i < medicines.size(); i++){
            cmbxMeds.addItem(medicines.get(i));
        }
    }//GEN-LAST:event_formWindowActivated

    private void cmbxPatIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxPatIdItemStateChanged
        // TODO add your handling code here:
        txtHistory.setText("");
        String patHistory = c.getPatHistory(cmbxPatId.getSelectedItem().toString());
        txtHistory.append(patHistory);
        
        cmbxAppointment.removeAllItems();
        ArrayList<String> appoints = c.getPatientApps(cmbxPatId.getSelectedItem().toString());
        for(int i = 0; i < appoints.size(); i++){
            cmbxAppointment.addItem(appoints.get(i));
        }
    }//GEN-LAST:event_cmbxPatIdItemStateChanged

    private void cmbxAppointmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbxAppointmentItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxAppointmentItemStateChanged

    private void btnCreatePrescriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePrescriptActionPerformed
        // TODO add your handling code here:
        String doctorid = DoctorUser.userID;
        String patientid = cmbxPatId.getSelectedItem().toString();
        String dosage = txtDosage.getText();
        String notes = txtPrescriptNotes.getText();
        String medicine = cmbxMeds.getSelectedItem().toString();
        
        Boolean complete = c.appendPrescription(doctorid, patientid, dosage, notes, medicine);
        if(complete == true){
            JOptionPane.showMessageDialog(null, "Prescription of: "+medicine+
                    " For Patient: "+patientid+" Requested Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnCreatePrescriptActionPerformed

    private void cmbxPatIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxPatIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxPatIdActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DoctorHome().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnMarkAttendedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkAttendedActionPerformed
        // TODO add your handling code here:
        String selectedApp = cmbxAppointment.getSelectedItem().toString();
        String selectedID = cmbxPatId.getSelectedItem().toString();
        Boolean attend = c.markAsAttended(selectedApp, selectedID);
        if(attend == true){
            JOptionPane.showMessageDialog(null, "Patient: "+selectedID+" Marked as Attended on: "+selectedApp, "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnMarkAttendedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppointmentControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppointmentControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppointmentControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppointmentControls.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppointmentControls().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppendNotes;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreatePrescript;
    private javax.swing.JButton btnMarkAttended;
    private javax.swing.JComboBox<String> cmbxAppointment;
    private javax.swing.JComboBox<String> cmbxMeds;
    private javax.swing.JComboBox<String> cmbxPatId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txtAppNotes;
    private javax.swing.JTextField txtDosage;
    private javax.swing.JTextArea txtHistory;
    private javax.swing.JTextField txtPrescriptNotes;
    // End of variables declaration//GEN-END:variables
}
